### ISSUE TITLE
代码显示异常？

### ISSUE THREAD

**Issue by shpirt** [emon100/blog#1]
![image](https://user-images.githubusercontent.com/41161865/95679681-0f8aef80-0c07-11eb-95c6-0640778b08b9.png)

好多意义不明的&#123 &#125。

ps：博主的文章写的很有意思😉

**Comment by emon100** [comment]
谢谢你的提醒，这些html转义符可能是老版本hexo渲染的bug。我已经把hexo升级到了最新版本并重新渲染了博客所有的页面。如果你那里显示仍有问题，你可以用ctrl+f5清除浏览器缓存来重加载页面。
